services:
  - type: web
    name: keybox-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PORT
        value: 10000
    healthCheckPath: /
    disk:
      name: data
      mountPath: /data
      sizeGB: 1