services:
  - type: web
    name: spfkeytracker-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PORT
        value: 10000
    healthCheckPath: /api/report
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

  - type: static-site
    name: keybox-tracker-frontend
    buildCommand: npm install && npm run build
    publishDir: build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: keybox-tracker-api
          type: web
          property: url